source 'https://rubygems.org'

gem 'rake'
gem 'rails'
gem 'simple_form'
gem 'bower-rails'
gem 'bootstrap-generators'
gem 'mongoid'
gem 'rspec-rails'
gem 'jasmine-rails'
gem 'cucumber-rails', require: false
gem 'aruba'
gem 'guard'
gem 'guard-rspec'
gem 'guard-jasmine'
